apiVersion: apps.baloise.dev/v1
kind: AppDeployment
metadata:
  name: appdeployment-sample
spec:
  replicaCount: 1
  image:
    repository: registry.example.tld/org/repo
    tag: "v1"
  network:
    http:
      ingress:
        host: example.example.tld
